# Advanced Claude Code GitLab Integration Example
#
# This example shows advanced configuration options

include:
  - remote: 'https://raw.githubusercontent.com/YOUR_USERNAME/claude-code-action/main/gitlab/templates/claude-code.yml'

variables:
  # Use Claude 3 Opus for more complex tasks
  CLAUDE_MODEL: "claude-3-opus-20240229"
  
  # Increase timeout for large codebases
  CLAUDE_TIMEOUT_MINUTES: "60"
  
  # Allow more conversation turns
  CLAUDE_MAX_TURNS: "50"
  
  # Custom branch prefix
  CLAUDE_BRANCH_PREFIX: "claude-suggestions/"

# Override specific Claude jobs if needed
claude-on-mr-comment:
  extends: .claude-base
  rules:
    # Only trigger for MRs with specific labels
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /needs-ai-review/'
      when: always
  script:
    - cd /tmp/repo
    - |
      # Add custom pre-processing
      echo "Running advanced AI review for MR #$CI_MERGE_REQUEST_IID"
      
      # Set custom instructions
      export CUSTOM_INSTRUCTIONS="Focus on security vulnerabilities and performance issues. Be extra thorough."
      
      # Run Claude
      claude-code-gitlab 2>&1 | tee $CI_PROJECT_DIR/claude-mr-${CI_MERGE_REQUEST_IID}.log

# Add a scheduled AI review job
scheduled-ai-review:
  extends: .claude-base
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - cd /tmp/repo
    - |
      # Review all open MRs
      echo "Running scheduled AI review of all open MRs"
      # This would need custom logic to iterate through open MRs